{"name": "Проверка удаления несуществующего курьера", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидаемый текст ошибки:'Курьера с таким id нет', фактический 'Курьера с таким id нет.'", "trace": "self = <test_delete_courier.TestDeleteCourier object at 0x0000020625C4D4C0>\n\n    @allure.title('Проверка удаления несуществующего курьера')\n    @allure.description('При удалении несуществующего курьера код ответа: 400, сообщение в теле : \"Курьера с таким '\n                        'id нет\"')\n    def test_delete_courier_with_not_existing_id(self):\n        delete_courier = DeleteCourier()\n        courier_id = DeleteCourier.generate_random_id()\n    \n        delete_courier.delete_courier(courier_id)\n    \n>       delete_courier.check_response_of_delete_courier_with_not_existing_id()\n\ntests\\test_delete_courier.py:24: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nendpoints\\delete_courier.py:51: in check_response_of_delete_courier_with_not_existing_id\n    self.check_response_message_of_delete_courier_with_not_existing_id()\nendpoints\\delete_courier.py:46: in check_response_message_of_delete_courier_with_not_existing_id\n    self.check_response_message(self.RESPONSE_MESSAGE_OF_DELETE_WITH_NOT_EXISTING)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <endpoints.delete_courier.DeleteCourier object at 0x0000020625CE18E0>, message = 'Курьера с таким id нет'\n\n    def check_response_message(self, message):\n>       assert self.response_json['message'] == message, (f\"Ожидаемый текст ошибки:'{message}', фактический \"\n                                                          f\"'{self.response_json['message']}'\")\nE       AssertionError: Ожидаемый текст ошибки:'Курьера с таким id нет', фактический 'Курьера с таким id нет.'\n\nendpoints\\base_point.py:20: AssertionError"}, "description": "При удалении несуществующего курьера код ответа: 400, сообщение в теле : \"Курьера с таким id нет\"", "steps": [{"name": "Генерирование случайного id", "status": "passed", "start": 1724956349398, "stop": 1724956349399}, {"name": "Удаление курьера", "status": "passed", "parameters": [{"name": "courier_id", "value": "65828307"}], "start": 1724956349399, "stop": 1724956349512}, {"name": "Проверка ответа удаления курьера c несуществующим id", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидаемый текст ошибки:'Курьера с таким id нет', фактический 'Курьера с таким id нет.'\n", "trace": "  File \"C:\\Users\\MSI\\PycharmProjects\\Sprint_7\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\MSI\\PycharmProjects\\Sprint_7\\endpoints\\delete_courier.py\", line 51, in check_response_of_delete_courier_with_not_existing_id\n    self.check_response_message_of_delete_courier_with_not_existing_id()\n  File \"C:\\Users\\MSI\\PycharmProjects\\Sprint_7\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\MSI\\PycharmProjects\\Sprint_7\\endpoints\\delete_courier.py\", line 46, in check_response_message_of_delete_courier_with_not_existing_id\n    self.check_response_message(self.RESPONSE_MESSAGE_OF_DELETE_WITH_NOT_EXISTING)\n  File \"C:\\Users\\MSI\\PycharmProjects\\Sprint_7\\endpoints\\base_point.py\", line 20, in check_response_message\n    assert self.response_json['message'] == message, (f\"Ожидаемый текст ошибки:'{message}', фактический \"\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "steps": [{"name": "Проверка статус кода удаления курьера c несуществующим id", "status": "passed", "start": 1724956349512, "stop": 1724956349512}, {"name": "Проверка тела ответа удаления курьера c несуществующим id", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидаемый текст ошибки:'Курьера с таким id нет', фактический 'Курьера с таким id нет.'\n", "trace": "  File \"C:\\Users\\MSI\\PycharmProjects\\Sprint_7\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\MSI\\PycharmProjects\\Sprint_7\\endpoints\\delete_courier.py\", line 46, in check_response_message_of_delete_courier_with_not_existing_id\n    self.check_response_message(self.RESPONSE_MESSAGE_OF_DELETE_WITH_NOT_EXISTING)\n  File \"C:\\Users\\MSI\\PycharmProjects\\Sprint_7\\endpoints\\base_point.py\", line 20, in check_response_message\n    assert self.response_json['message'] == message, (f\"Ожидаемый текст ошибки:'{message}', фактический \"\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1724956349513, "stop": 1724956349513}], "start": 1724956349512, "stop": 1724956349516}], "start": 1724956349398, "stop": 1724956349518, "uuid": "be60b96b-ea5f-481a-ae75-70686eb4e230", "historyId": "ced1ce7bccdbb23f6bf17639223fb6b5", "testCaseId": "ced1ce7bccdbb23f6bf17639223fb6b5", "fullName": "tests.test_delete_courier.TestDeleteCourier#test_delete_courier_with_not_existing_id", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_delete_courier"}, {"name": "subSuite", "value": "TestDeleteCourier"}, {"name": "host", "value": "DESKTOP-AS1GOJN"}, {"name": "thread", "value": "5404-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_delete_courier"}]}